env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
os:
  - linux
  - osx
language: rust
rust:
  - 1.26.1
  - nightly-2018-05-29
sudo: false
cache:
  cargo: true
before_script:
  - if ! cargo prune --version | grep -q "0.1.8"; then
      cargo install cargo-prune --version="0.1.8" --force;
    fi
  - if [ "${TRAVIS_RUST_VERSION}" = nightly-2018-05-29 ]; then
      rustup component add rustfmt-preview --toolchain nightly-2018-05-29 &&
      cargo install --version=0.0.206 --force clippy;
    fi
script:
  - if [ "${TRAVIS_RUST_VERSION}" = 1.26.1 ]; then
        (
            set -x;
            cargo test --verbose --release --no-default-features
        );
    elif [ "${TRAVIS_OS_NAME}" = linux ]; then
        (
            set -x;
            cargo fmt -- --check &&
            cargo clippy --profile=test -- -D warnings
        )
    fi
before_cache:
  - cargo prune
